apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      version: blue
  template:
    metadata:
      labels:
        app: springboot
        version: blue
    spec:
      containers:
        - name: backend
          image: shamkumbhar47/backend:blue   # 👈 blue backend image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: blue
            - name: DB_HOST
              value: mysql-service   # removed namespace suffix
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: quantumsoft
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-blue
spec:
  type: ClusterIP
  selector:
    app: springboot
    version: blue
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
      version: green
  template:
    metadata:
      labels:
        app: springboot
        version: green
    spec:
      containers:
        - name: backend
          image: shamkumbhar47/backend:green   # 👈 green backend image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: green
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: quantumsoft
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-green
spec:
  type: ClusterIP
  selector:
    app: springboot
    version: blue
  ports:
    - port: 8080
      targetPort: 8080
